### PR TITLE
Protect from circular references with inside-out storage for callbacks

### PR DESCRIPTION
**Pull request by kraih**
Here's a pull request, as requested on IRC. Storing the callbacks outside the promise object protects from many [commonly occuring circular references](https://gist.github.com/kraih/11276761) with closures. Sorry for the lack of unit tests, can't think of a good test case at the moment.

### CODE REVIEW

**Comment by kraih** [comment]
Closed this pull request since i no longer recommend handling callbacks this way. The circular references prevented by it are mostly harmless and will not lead to memory leaks. You could argue that hiding a few false positives from `Devel::Cycle` is worth it, but i'm not sure about that yet.

**Comment by stevan** [comment]
@kraih how do you recommend handing callbacks these days?

**Comment by kraih** [comment]
@stevan Just like you do now, explicitly clear `$deferred->{resolved}` and `$deferred->{rejected}` once the promise has been resolved to break all cycles.

**Comment by stevan** [comment]
Oh, I thought you meant not handling callbacks with Promises at all, but still that is a good bit of advice.

**Pull request closed without merging**
