### PR TITLE
function attribute turning funcs into promises

### PR DESCRIPTION
**Pull request by yanick**
Depends on #53 

Purely sugary goodness. See the example in the POD for how it can be used.

### CODE REVIEW

**Comment by yanick** [comment]
Hmmm... The attributes as they are don't work with anonymous subs. Will have to work that out before merging it to master.

**Comment by stevan** [comment]
Lemme think about this one a bit,... I like it in general, but the different API for anon-subs and named-subs kind of bugs me, though even as I type this it is kind of growing on me. But the closeness of `defer` and `deferred` is also a little odd, specifically because they are functionally very different but nominally(?) very close.

**Comment by yanick** [comment]
> I like it in general, but the different API for anon-subs and named-subs kind of bugs me

Yeah, I had a sad too when I realized that the attribute can't be used on anon subs like I did on regular subs, as there is no symbol to munge. 

> But the closeness of defer and deferred is also a little odd

Can't deny I suck a wee bit at finding good names. I thought of `defer_sub`, then figured out that 

```perl
my $sub = defer_sub sub { ... };
```

would begin to sound like smurf-speak. I was thinking about `promisify` as well.... Or maybe reuse `Defer` so that it can be written

```perl
my $sub = Defer( sub { ... } );
```

(... meh, that one doesn't look much better)

**Comment by yanick** [comment]
(rebased the branch off your master, not mine. Still depends on #53)

**Comment by yanick** [comment]
I need to revisit the branch.

**Pull request closed without merging**
