### PR TITLE
Update documentation for Dist:Zilla

### PR DESCRIPTION
**Pull request by athos-ribeiro**
Installation instructions were outdated

### CODE REVIEW

**Comment by stevan** [comment]
Dist::Zilla should only be required if you are installing from GitHub or planning to do development work on the module itself ("author" time dependency). If installed from CPAN it should not be required. Can you explain the issue that lead you to submit this patch?

Thanks, 

Stevan

**Comment by athos-ribeiro** [comment]
Oh, I see, the README information was probably for tarball distribution, right?

Well, I got your dist for cpan PR-Challenge (http://neilb.org/2014/11/29/pr-challenge-2015.html), and 1st thing I noticed in the repo was the absence of instructions for using Dist::Zilla! :)

**Comment by stevan** [comment]
Yes, the README is meant to be distributed with the module. 

If you are looking for something to work on related to this module you might want to take a look at this older pull-request (https://github.com/stevan/promises-perl/pull/32). It has been closed, but there is likely some code improvements that could be pulled from it. 

You could also look over the RT queue (https://rt.cpan.org/Public/Dist/Display.html?Name=Promises) many of these issues could probably be closed, but again there might be some good parts within them that can be applied.

Additionally, you could look into some of the other Promise modules (https://metacpan.org/pod/Promises6 and https://metacpan.org/pod/AnyEvent::Promise in particular) and see if there is anything useful in their implementations that could be merged back to this module. 

Of course if you have any ideas yourself about improvements, I am always open to suggestions as well.

And lastly, thanks for participating in the CPAN PR-challange!  :)

- Stevan

**Comment by yanick** [comment]
As Stevan said, the README is for the final cpan disto. I won't merge this ticket in, but thanks for submitting it!

**Pull request closed without merging**
