### PR TITLE
add collect_props

### PR DESCRIPTION
**Pull request by yanick**
Saw it on the JavaScript side. Looks like a good idea.

### CODE REVIEW

**Comment by yanick** [comment]
Btw, if you want to keep the main Promises distro minimal, I can always add those helper functions in a Promises::More distro. 

Or, if you need help to merge and prepare a new release, just wave in my direction. :-)

**Comment by stevan** [comment]
So my only issue with this is the name, I had no clue what `props` meant at first. A quick look at the docs answered all my questions, but ... well, ... I guess the name just feels more JS then Perl. Does that make sense?

Maybe just make `collect` polymorphic, given a list or array ref it does what it does now, but given a hash ref, it does what collect_props does. Does that sound reasonable?

**Comment by yanick** [comment]
Actually, I think I stumbled into a more graceful solution in one of the later PRs. 

In #54, I added `flat_collect`, which is like `collect` but returns the results of the promises as a single list instead of a list of arrayrefs.  Using that, the use case of `collect_props` 

```
collect_props(
   this => 'blah',
   that => $promise,
)->then( sub($props) {
   say "a little of ", join ' and ', $props->@{qw/ this that/};
});

```

can be  rewritten  as

```
flat_collect(
   this => 'blah',
   that => $promise,
)->then( sub(%props) {
   say "a little of ", join ' and ', @props{qw/ this that/};
});

```

The function is more general, and the code is just as straight-forward. I like. Give me a few hours, and I'll rework the documentation and the PR to take this new direction.

**Comment by yanick** [comment]
There we go. Whatchathink?

**Comment by yanick** [comment]
I have to revisit the branch.

**Pull request closed without merging**
